sudo: false
language: node_js
node_js:
- '6.0'
cache:
  directories:
  - dmriprepViewer/node_modules
branches:
  only:
  - master
notifications:
  email: false
before_script:
- cd dmriprepViewer
- npm prune
script:
- npm install
- npm run build
after_success:
- bash ./deploy.sh
env:
  global:
  - GH_USER: nipy
  - GH_REPO: dmriprep
  - secure: raeexu68fu/Hu4Ey0VkP3ljvAJut2X8xRAkTXO9nL6HlWQGt1pjYhXSxaLLZVQpgpDcDeOziUUCb4y7UALFHTkIrYrzp/Jq3Cn10tmsItEMAhH0cfzTuMr0Huhl/Zeiw67Qn16W7xpYEtV7zHBOYicQIFvzAOhNWDy/A/9c7XkKsEU47FqN/vxodCv+WMHQyvuM3ceaofccF+mVekAg7PztPrukzpwP+uishNfSeoHI3WeUDjX82bQZ3KE/oRHrB+YCB5rFg0wfekfsUnkyhS9HWF9CECM5mKWcPle0AZpjQXODrUIXk8dRSAprAzD1XGxRzmYG3nYPGx9a6gm6ofueHbLPery/0cLVYNX4IHBR2UpW6aA9VsgMBgG8LAdGiMqvvio2CZ+/tGdmIXx5twRCTGaJ4qJUdyyL881ChaUl8rBde7R8EtCBThKeV8Tnnun2PfLPt12qAc+EAc1r6a9zf/Mb8ahjTrZSU1heUn5irs44KvJk+QuftW9hF6hIvBfug7SHBIAdvyCd8TjMNShJNVPqQZU6NWSwTAGAj4Y/QsocvxYRoKHIhpyHbMZ+Lj+P27VfNYdkTe/viQcLEg8x4YYHCaKiYl4iwepEtyevtbtzUtb1Ba5clotgisw/PFao9q6GrWuy57eb/ZM8aKSHfb4JhN0swmi1t0uBOzP0=
