sudo: false
language: node_js
node_js:
- '6.0'
cache:
  directories:
  - dmriprepViewer/node_modules
branches:
  only:
  - master
notifications:
  email: false
before_script:
- cd dmriprepViewer
- npm prune
script:
- npm install
- npm run build
after_success:
- bash ./deploy.sh
env:
  global:
  - GH_USER: nipy
  - GH_REPO: dmriprep
  - secure: VmTfAChlLlC8WfK0QS9UzfTdI58so7YLkQdlTbB3WptqKIPDcGUSUjyB5ow9BO6nwupN0/zxaM3rneWJeJ7oEBQWGrbpdDkLWkCPB6htjECmUhfyWJccBH4ZnvVjDQH9Wl5SgNieJjGzI8QBLwnsvjzafH3VkP3SWFvqq4J3bGyDb97MUkWgDLdjy+3HsX6Ye7HCkYnLhi2BSwON/asQLd+Pr1FOv+P2tsJgwz9X4gkzws8gP5jGM4J5jxwYRUQKZKjgiEvDZbL0OqTvH/jxELKwcuIhDrqVeemZn5wWLRt7pvFUAzAwUliE0/NROUFi57RhU9NrwOZAo7ek3muM33AgBGodpkFJJ9vmsMJf5Diz71YN3xvMMD2vlfDByjcPOqYu/uM5o6sbuLZNDc+NExlsSSskMOnOBGz5e+Exo6c+X6Dxqx3rT6jmBPVTv7E9RiL1wwXF18fpCDrXwZb/mmxxbB0Bm3x/etIbi/mmbGlPo8K2GgOyzACPK3DHA6lRPd97qwU5cp/+7IWr7LWrVxAl6VS19/GIkVVlmBS3/7IJSg4ANgLAVZzXrcRcJTEY2xsF3TFJm840v6ArkFEogj84dGcxr1o9oLFLh2ZBSatoqSwdL8NezJruoOYDGzW37thp51iAHwNZ+Zfpv/PIcmWRrsBbhV+FA8KkFxmfIR0=
