name: dmriprep
channels:
   - conda-forge
dependencies:
   - python=3.6
   - boto3
   - dask
   - dipy
   - graphviz
   - ipython
   - pandas
   - tqdm
   - pip:
     - "--editable=git+https://github.com/nipy/nipype@35b58cdb59a900430f4b9639e220c8408341805d#egg=nipype"
     - bids
     - duecredit
