name: dmriprep
channels:
   - conda-forge
dependencies:
   - python=3.6
   - boto3
   - dask
   - dipy
   - graphviz
   - ipython
   - pandas
   - tqdm
   - pip:
     - "--editable=git+https://github.com/akeshavan/nipype@fcb90bea6ed5f0e47b1d216ba04352b4038ad13d#egg=nipype"
     - "--editable=git+https://git.fmrib.ox.ac.uk/matteob/eddy_qc_release@57bb11da6a634c4195593fbc439ba9f8998157b0#egg=eddy_qc"
     - bids
     - duecredit
